name = "ReversedStrings"
uuid = "d6a58270-6f46-44a2-ab4b-2a767377cb4b"
authors = ["Gregor Kappler"]
version = "0.1.0"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"

[compat]
julia = "1"
AutoHashEquals = "0.2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
